### ISSUE TITLE
UX / Styling adjustments

### ISSUE THREAD

**Issue by cooper-joe** [dhis2/import-export-app#664]
# Background
The QA team requested that I take a look at this app. I think a UX review should have happened much earlier, there is not much time to make changes. I have noted down the following adjustments that will make this app more consistent with the DHIS2 design system and other apps. Please excuse the shortness of these notes, time is very limited. Please ask on slack if there are any points that are not clear and I will clarify.

### Mockups
There are limited mockups that I created to help communicate the changes. [Design mockups can be found here](https://www.sketch.com/s/30badb5c-7adf-440c-9b78-97527aff53c2). Padding/spacing/font-size/styling can be checked in 'Inspector' mode of the mockups. Note that there is no functionality included in the mockups.

# Requested changes

## Global changes 

- [x] global background for content area of `grey050`
- [x] #fff should never be used for text/icons. Use `ui` color `grey900`.
- [x] reuse page header + intro text styles from sms-configuration app that has recently gone through a ux review. See mockup for examples
- [x] page content does not need to put inside card containers as there is only a single container. content can sit directly on the page. (again, see sms-config for an example). job summary etc. can still live inside a card when applicable.
- [x] all labels that are current ALLCAPS and #fff should be restyled to be `font-size: 14px, font-weight: 500, color: grey800`. See mockup where all these have been restyled. Note that some have been replaced by other types of headings.
- [x] reduce maximum width of content for all import/export pages to 800. (not job overview)
- [x] for all import pages, Dry run button text: 'Start dry run', Import button text: 'Start import'
- [x] padding between each section and action buttons - make it clear they do not belong to the same section (all sections have margin-bottom: 48px;, see mockup)

## sidebar

- [x] reuse background and sidebar styles recently implemented in sms-configuration app
- [x] job overview: do not use yellow background. if a status is needed, use a colored dot next to the title (see mockup)

## data import

- [x] add header for 'basic options', so that the 'advanced options' header makes sense. reuse header style from sms-config.
- [x] file: use the built-in label that comes with `FileInputField`. More descriptive label and include help text for valid file types, see mockup.
- [ ] file format: is this necessary? can we not infer this from the extension?
- [x] strategy: update label to 'import strategy', update labels to be more descriptive (not sure I got Delete correct?) use vertical radio buttons because of longer label text.
- [x] preheat cache. use checkbox, switches are only for 'ongoing' actions like a job running constantly that can be turned on off. We need to improve the text to explain this feature - it is faster for large imports but at what cost? Why shouldn't every import use this if its faster, does it consume more resources? Add this as help text, see mockup.
- [x] more options -> advanced options, use chevron up/down instead of plus/minus to move away from metaphorical add/delete.
- [x] all fields in advanced (ID schemes): use labels provided by `ui` `select` fields. Max width of 360 for these fields, the content is short.
- [x] skip checking: use checkbox (reasons outlined above). See mockup for label/helptext
- [x] adjust dry run help text

## event import

- [x] all the same changes as 'data import' that apply here

## GML import

- [x] all the same changes as 'data import' that apply here

## Metadata import

- [x] all the same changes as 'data import' that apply here
- [x] more help text to explain fields: import report mode, preheat mode, atomic mode, merge mode, flush mode. How can we help the user to understand what these options do? I can help write help texts, but need to know more about the features.
- [x] skip sharing: use a checkbox and I think this option should be inverted, so that a true boolean checked box means 'include sharing' (unless I have misunderstood this feature, my understanding is that it imports the sharing settings for metadata too)
- [x] skip validation: use a checkbox. improve the label or include helptext to better explain what this feature does.
- [x] inclusion strategy: help text to help the user understand what the difference is between options (we can discuss)

## TEI import

- [x] all the same changes as 'data import' and especially 'metadata import' with the relevant helptexts etc.

## Data export

- [x] slightly adjust intro text in header, see mockup
- [x] organisation unit: change label, see mockup
- [x] organisation unit: tree wrapper should have white background
- [x] include children: use checkbox. change label to 'Include organisation units inside selection' (Best not to use term 'child' as it is easily confused for 'child' TEIs.)
- [x] data sets: use a `ui` `transfer` which allows for easy select all, deselect etc. More suited to this task that a long list of checkboxes
- [x] start/end date: include an extra label "date range to export data for", then use the built-in labels for `input` for start/end date fields. See mockup for example. Also put these inputs on a single line
- [x] date/format/compression: reorder fields so they are the same as in event export (date, format, compression)
- [x] include deleted: use checkbox. Use label: "Include deleted data in export"
- [x] ID schemes: same feedback as in data import.
- [x] Export button: use label "Export data"

## Event export

- [x] slightly adjust intro text in header, see mockup
- [x] organisation unit: adjust label, see mockup
- [x] organistion unit: there is version of the org.unit tree in `ui` [specificially for selecting a single unit](https://ui.dhis2.nu/demo/?path=/story/organisationunittree--single-selection), use that instead of radio buttons
- [x] organisation unit: tree wrapper should have white background
- [x] include children: in Data export the 'include children' option is directly underneath org unit selection. Here in event export it is the last option inside the 'more options'. I think this should be consistent and the 'inclusion mode' should be directly underneath the org unit selection. Have included this in mockup
- [x] program selection: use `ui` filterable `select` , [example](https://ui.dhis2.nu/demo/?path=/story/singleselect--with-filter-field)
- [x] program stage: use built-in label in `ui` `select` Do not adjust styles of the content inside the `select` (currently is set to bold and uppercase) Remove brackets around "[ All program stages ]" and use label "All stages".  Reduce field width to 480px;
- [ ] program stage: this option should only be included if the selected program is of type `tracker`, it should be hidden if selected program is `single-event`. 
- [x] date: same feedback as data export
- [x] advanced options: same feedback as data export
- [x] Export button: use label "Export events"

## Metadata dependency export

(no mockup here, short on time)

- [x] Adjust intro text in header to "Export metadata dependencies, such as data sets and programs, including related metadata objects, in XML or JSON format"
- [x] Object type: reduce field width to 480px, use built-in `select` label, do not adjust styles of the `select` content
- [x] Object: reduce field width to 480px, use `regular`, not `dense` for consistency. use built-in `select` label, do not adjust styles of the `select content`
- [x] same as most other pages, adjust labels
- [x] skip sharing: see Metadata import for feedback on this
- [x] Export button: use label "Export metadata dependencies"

## Metadata export

(no mockup, short on time)

- [x] Adjust intro text in header to: "Export metadata, such as data elements and organisation units, in XML, JSON or CSV format."
- [x] adjust headers of checkbox groups to use styles used throughout (`font-size: 14px, font-weight: 500, color: grey800`.)
- [x] skip sharing: see Metadta import for feedback
- [x] Export button: use label "Export metadata"

## TEI export

- [x] Adjust intro text in header to: "Export tracked entity instances in XML, JSON, JSONP or CSV format."
- [x] Org unit selection mode: same feedback as in Event export: adjust labels to remove references to 'children'
- [x] Org unit selection mode: does the last two '...for the current user' selections ignore the selection made inside the org unit tree above? we need to reflect this in the labels (or rethink this)
- [x] Filter by: change 'tracked entity' label to 'tracked entity type'
- [x] Tracked entity type filter: use a `ui` `select` with filter functionality
- [x] Program filter: use a `ui` `select` with filter functionality, covered above in Event export
- [x] program status: change field label and 'all label', see mockup
- [x] follow-up status: change field label and 'true'/'false' labels, see mockup
- [x] date range: similar feedback to elsewhere with labels and using `input` labels etc.
- [x] date range: label, I've put 'registration date range', but is it actually enrollment date, or last updated date? we should be clear what type of date is used to filter here.
- [x] filter by last updated: 
  - [x] change label to 'filter by last updated date'
  - [x] change all option labels, see mockup
  - [x] reuse start/end date inputs as used elsewhere (on a single line, etc.)
- [x] Assigned user mode: adjustlabel options
- [x] Assigned user mode, selected users: use `ui` `transfer` with built in filtering for user selection
- [x] Include deleted: use checkbox, as elsewhere
- [x] Include all attributes: use checkbox
- [x] ID schemes, adjust max-widths, same feedback as elsewhere
- [x] Export button: use label "Export tracked entity instances"

## Job overview

- Haven't gotten to this part yet. Will update if there is time.

**Comment by amcgee** [comment]
@awgaan @Birkbjo I agree with @cooper-joe that this is quite important, the import-export app is a critical workflow piece.  Let me know how I (or anyone with bandwidth on @dhis2/team-apps) can help to make sure we get everything in before the hard freeze - let's not let it slip unintentionally.

**Comment by amcgee** [comment]
@cooper-joe should we reopen this or can it be closed?

**Comment by cooper-joe** [comment]
There's two outstanding todos in the list that I think would improve the user experience. I'm not sure why they were skipped. I can open them as jira tickets to followup and we can close this.
